### ISSUE TITLE
Cannot disable Hinterland from nbextensions configurator

### ISSUE THREAD

**Issue by maximz** [ipython-contrib/IPython-notebook-extensions#658] opened 2016-07-05 19:16 UTC
I'm running Jupyter 4.1.0. I wanted to disable Hinterland after trying it briefly, and was unable to disable it through nbextensions configurator. The configurator showed Hinterland as disabled, but every existing and new notebook would still have Hinterland enabled, even after restarting the jupyter process. Furthermore, Hinterland was still listed after running this in a cell:

```
from IPython.html.services.config import ConfigManager
from IPython.display import HTML
ip = get_ipython()
cm = ConfigManager(parent=ip, profile_dir=ip.profile_dir.location)
extensions =cm.get('notebook')
table = ""
for ext in extensions['load_extensions']:
    table += "<tr><td>%s</td>\n" % (ext)

top = """
<table border="1">
  <tr>
    <th>Extension name</th>
  </tr>
"""
bottom = """
</table>
"""
HTML(top + table + bottom)
```

Thus, the configurator does not properly disable Hinterland. To fully disable, I had to run: `jupyter nbextension disable usability/hinterland/hinterland`

**Comment by jcb91** [comment] 2016-07-06 11:10
Intriguing! Ok, a few questions:

1. Can you get this to happen repeatably? If so, what steps are needed to reproduce?
2. When following the same process, does this problem happen with any other nbextension (I would guess it should), or just hinterland (that would be weird!)
3. how did you enable hinterland? Did you use the configurator, the `jupyter nbextension enable` command, a javascript notebook cell, or several methods?

My off-the-top-of-the-head guess is that this is either down to having multiple versions of the config file in different places which conflict, or a bug in configurator js (which should go to an issue into the configurator repo at [Jupyter-contrib/jupyter_nbextensions_configurator](https://github.com/jupyter-contrib/jupyter_nbextensions_configurator)).

**Comment by maximz** [comment] 2016-07-06 19:42
Yes, just reproduced it with the following steps:

1. Open jupyter homepage, go to nbextensions tab, enable Hinterland
2. Open a new notebook, observe the Hinterland completion when you start typing `print`
3. Go back to nbextensions tab and disable Hinterland
4. Refresh the notebook, still have Hinterland completion --> should not be there.
5. Create another notebook, still have Hinterland completion --> also should not be there.
6. Run `jupyter nbextension disable usability/hinterland/hinterland`
7. Return to any notebook or create a new one, and now Hinterland completion does not occur

I enabled Hinterland from the nbextensions tab.

I just tried the same with the spellchecker extension -- I still see typo highlighting after disabling the extension in the configurator UI and then refreshing an old notebook or making a new notebook.

**Comment by jcb91** [comment] 2016-07-06 23:45
hmm, sounds odd... I'll investigate. Further questions, what's the output of

    jupyter notebook --version

and

    jupyter nbextensions_configurator --version

?

**Comment by maximz** [comment] 2016-07-07 19:13
Thanks for your help!
```
> jupyter notebook --version
4.1.0
> jupyter nbextensions_configurator --version
0.1.1
```

**Comment by jcb91** [comment] 2016-07-08 10:45
Ah you're welcome. I'm away from a computer for a few days now, but from my
rudimentary investigations to date it seems to me like this is related to
the notebook implementation of the config service, rather than directly the
configurator. For a quick fix, I think it should work correctly for
notebook versions >= 4.2 as a result of improvements made to the config
service, if you're in a position to upgrade. Of course, I'd like to get it
working correctly for all notebook versions once I get a chance to look at
it properly, though how possible/sensible that is will of course depend on
how much altering the notebook machinery would need...

**Comment by maximz** [comment] 2016-07-08 19:23
Thanks, I'll try the upgrade to see if that fixes it.

**Comment by jcb91** [comment] 2016-07-13 17:14
So, I've finally figured out what was going on here. Essentially, before version 4.2, the notebook javascript just loads any extensions in the `load_extensions` config value, regardless of whether the key's value is `true` or `false`. I missed the fact that this was only fixed in notebook 4.2, and had updated the configurator to set the `false` value (rather than deleting the key) in order to play nicely with the `jupyter nbextension list` command (also new in 4.2), without noticing that it broke support for notebook < 4.2. I didn't notice because my automated testing only checked the server-side json (which was correctly modified), not whether the extension *actually got loaded*. The behaviour and test deficiency are now fixed in PR https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator/pull/9

**Comment by maximz** [comment] 2016-07-13 19:48
Great!

**Closed** 2016-07-13 23:16 UTC

**Comment by jcb91** [comment] 2016-07-13 23:49
for anyone who has run into this problem already, you may need to run a quick `pip install --upgrade jupyter_nbextensions_configurator`

**Comment by kgaurav27** [comment] 2021-05-15 06:27
switch off hint , that shown in image , It will work proply . 
 jupyter / Help/ continuous help/ off
